name: rick_morty_app
description: "An app about Rick and Morty characters."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  cached_network_image: ^3.4.1
  clock: ^1.1.2
  cupertino_icons: ^1.0.8

  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_localizations:
    sdk: flutter
  flutter_pretty_dio_logger: ^3.0.0
  get_it: ^8.2.0
  go_router: ^16.2.5
  http_parser: ^4.1.2
  infinite_scroll_pagination: ^5.1.1
  lottie: ^3.3.2
  mime: ^2.0.0
  path: ^1.9.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/res/lotties/

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/res/fonts/Poppins-Light.ttf
          weight: 300
        - asset: lib/res/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/res/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: lib/res/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: lib/res/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: lib/res/fonts/Poppins-MediumItalic.ttf
          weight: 600
          style: italic
        - asset: lib/res/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: lib/res/fonts/Poppins-SemiBoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/res/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: lib/res/fonts/Poppins-BoldItalic.ttf
          weight: 800
          style: italic
        - asset: lib/res/fonts/Poppins-ExtraBold.ttf
          weight: 900
        - asset: lib/res/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 900
          style: italic
